### ISSUE TITLE
invalid ssl/tls certificates

### ISSUE THREAD

**Issue by caemor** [nastevens/rust-embedded-provisioning#1]
Both:
- [https://embedonomicon.rust-embedded.org/](https://embedonomicon.rust-embedded.org/) and
- https://rust-embedded.org/
lead to invalid certificate errors atm.

Basically they both seems to use the *.github.com/*github.io certificates but as the domain isn't any of the subdomains of github anymore this leads to an error/warning in most browsers.

E.g.
```
embedonomicon.rust-embedded.org uses an invalid security certificate. 

The certificate is only valid for the following names: www.github.com, *.github.io, *.githubusercontent.com, *.github.com, github.com, github.io, githubusercontent.com 

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by nastevens** [comment]
With the reorg per https://github.com/rust-embedded/wg/issues/208, all docs are now hosted under https://docs.rust-embedded.org, and TLS certs are lined up correctly for that. However, the following will still fail if you try to go directly to the `https` version - this is because the following pages actually host a HTTP redirect and there are certificate issues going from AWS to Github:

* https://www.areweembeddedyet.com
* https://www.rust-embedded.com
* https://areweembeddedyet.com
* https://rust-embedded.com

I think at this point the right way to fix this will be to get TLS certs for those specific domains (probably through LetsEncrypt) and then run a lambda at those endpoints to do the HTTP redirect.

**Comment by caemor** [comment]
Should I leave this open to track the further steps in the future or can I close it?

**Comment by nastevens** [comment]
I created #10 to track the more specific issue, so this can be closed. Thanks for reporting this originally!
