### ISSUE TITLE
contents of book.rust-embedded.org and rust-embedded.github.io/book are not the same

### ISSUE THREAD

**Issue by japaric** [nastevens/rust-embedded-provisioning#2]
https://book.rust-embedded.org/

https://rust-embedded.github.io/book/

I thought the problem was that the CNAME file was missing from the book repository but I added it in rust-embedded/book#24 and the problem persists 13 hours after the change.

**Comment by ryankurte** [comment]
https://book.rust-embedded.org/ currently points to a server run by @jamesmunns (see: [L#63](https://github.com/nastevens/rust-embedded-provisioning/blob/3988d0c630b884477c9c078af6b86276aef728f6/route53.tf#L36)) rather than the github.io version.

I've opened a PR, but it will also all be superseded by https://github.com/rust-embedded/wg/issues/208.

**Comment by ryankurte** [comment]
@nastevens I'm seeing 404's and certificate errors for both https://github.com/rust-embedded/book and https://github.com/rust-embedded/embedonomicon now, looks like we've got something wrong...

**Comment by nastevens** [comment]
@ryankurte It looks like the custom domain settings got cleared somehow on both those repos. I've reset them, hopefully that clears things up. According to GitHub it might take up to an hour https://help.github.com/articles/troubleshooting-custom-domains/#https-errors

**Comment by nastevens** [comment]
Closing as https://github.com/rust-embedded/wg/issues/208 has been implemented and all docs are under docs.rust-embedded.org
